// <auto-generated />
using System;
using ASPNetCore_EF_Employees.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPNetCore_EF_Employees.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    partial class EmployeesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASPNetCore_EF_Employees.Models.Department", b =>
                {
                    b.Property<int>("Deptno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Deptno"), 1L, 1);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Loc");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dname");

                    b.HasKey("Deptno");

                    b.ToTable("Dept", (string)null);

                    b.HasData(
                        new
                        {
                            Deptno = 10,
                            Location = "Kaai",
                            Name = "DT"
                        },
                        new
                        {
                            Deptno = 20,
                            Location = "Danseart",
                            Name = "RITCS"
                        },
                        new
                        {
                            Deptno = 30,
                            Location = "Bloemenhof",
                            Name = "MMM"
                        },
                        new
                        {
                            Deptno = 40,
                            Location = "Jette",
                            Name = "GL"
                        });
                });

            modelBuilder.Entity("ASPNetCore_EF_Employees.Models.Employee", b =>
                {
                    b.Property<int>("Empno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Empno"), 1L, 1);

                    b.Property<double>("Commission")
                        .HasColumnType("float")
                        .HasColumnName("Comm");

                    b.Property<int>("Deptno")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hiredate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Job")
                        .HasColumnType("int");

                    b.Property<int?>("Mgr")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ename");

                    b.Property<double>("Salary")
                        .HasColumnType("float")
                        .HasColumnName("Sal");

                    b.HasKey("Empno");

                    b.HasIndex("Deptno");

                    b.HasIndex("Mgr");

                    b.ToTable("Emp", (string)null);

                    b.HasData(
                        new
                        {
                            Empno = 100,
                            Commission = 100.0,
                            Deptno = 10,
                            Hiredate = new DateTime(2010, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = 2,
                            Name = "Steve",
                            Salary = 1000.0
                        },
                        new
                        {
                            Empno = 200,
                            Commission = 0.0,
                            Deptno = 10,
                            Hiredate = new DateTime(2016, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = 3,
                            Mgr = 100,
                            Name = "Wim",
                            Salary = 1000.0
                        });
                });

            modelBuilder.Entity("ASPNetCore_EF_Employees.Models.Employee", b =>
                {
                    b.HasOne("ASPNetCore_EF_Employees.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Deptno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPNetCore_EF_Employees.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("Mgr");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
